import { Repository } from "@/types/repository";

export const REPOSITORIES_DATA: Repository[] = [
  {
    id: "1",
    name: "design-system",
    isPublic: true,
    language: "React",
    size: 7320,
    lastUpdatedDateInDay: 1,
    description: "A comprehensive design system built with React",
  },
  {
    id: "2",
    name: "e-commerce-platform",
    isPublic: false,
    language: "TypeScript",
    size: 12480,
    lastUpdatedDateInDay: 3,
    description: "Next.js based e-commerce solution",
  },
  {
    id: "3",
    name: "data-visualization",
    isPublic: true,
    language: "JavaScript",
    size: 4200,
    lastUpdatedDateInDay: 5,
    description: "Interactive data visualization components",
  },
  {
    id: "4",
    name: "api-gateway",
    isPublic: false,
    language: "Go",
    size: 2800,
    lastUpdatedDateInDay: 2,
    description: "API Gateway service with authentication",
  },
  {
    id: "5",
    name: "ml-pipeline",
    isPublic: true,
    language: "Python",
    size: 15600,
    lastUpdatedDateInDay: 7,
    description: "Machine learning pipeline implementation",
  },
  {
    id: "6",
    name: "mobile-app",
    isPublic: true,
    language: "Flutter",
    size: 8900,
    lastUpdatedDateInDay: 6,
    description: "Cross-platform mobile application",
  },
  {
    id: "7",
    name: "graphql-api",
    isPublic: false,
    language: "Node.js",
    size: 5600,
    lastUpdatedDateInDay: 10,
    description: "GraphQL API for managing user data",
  },
  {
    id: "8",
    name: "blog-platform",
    isPublic: true,
    language: "Vue.js",
    size: 3100,
    lastUpdatedDateInDay: 8,
    description: "A blogging platform built with Vue.js",
  },
  {
    id: "9",
    name: "serverless-functions",
    isPublic: true,
    language: "JavaScript",
    size: 2200,
    lastUpdatedDateInDay: 4,
    description: "Collection of serverless functions",
  },
  {
    id: "10",
    name: "weather-app",
    isPublic: true,
    language: "React Native",
    size: 4100,
    lastUpdatedDateInDay: 9,
    description: "A weather application built with React Native",
  },
  {
    id: "11",
    name: "task-manager",
    isPublic: false,
    language: "Ruby on Rails",
    size: 7200,
    lastUpdatedDateInDay: 12,
    description: "A task management system for teams",
  },
  {
    id: "12",
    name: "authentication-service",
    isPublic: true,
    language: "Go",
    size: 5000,
    lastUpdatedDateInDay: 15,
    description: "User authentication service with JWT",
  },
  {
    id: "13",
    name: "crypto-dashboard",
    isPublic: true,
    language: "Angular",
    size: 7500,
    lastUpdatedDateInDay: 20,
    description: "Real-time cryptocurrency price tracking dashboard",
  },
  {
    id: "14",
    name: "image-optimizer",
    isPublic: false,
    language: "Python",
    size: 3500,
    lastUpdatedDateInDay: 18,
    description: "Image optimization service for web applications",
  },
  {
    id: "15",
    name: "video-streaming",
    isPublic: true,
    language: "JavaScript",
    size: 9300,
    lastUpdatedDateInDay: 13,
    description: "A video streaming platform with user subscriptions",
  },
  {
    id: "16",
    name: "social-media-dashboard",
    isPublic: false,
    language: "TypeScript",
    size: 11500,
    lastUpdatedDateInDay: 21,
    description: "Admin dashboard for managing social media posts",
  },
  {
    id: "17",
    name: "chat-application",
    isPublic: true,
    language: "React",
    size: 6400,
    lastUpdatedDateInDay: 17,
    description: "Real-time chat application with WebSockets",
  },
  {
    id: "18",
    name: "data-pipeline",
    isPublic: true,
    language: "Java",
    size: 9000,
    lastUpdatedDateInDay: 22,
    description: "ETL data pipeline for big data processing",
  },
  {
    id: "19",
    name: "task-automation",
    isPublic: false,
    language: "Python",
    size: 8700,
    lastUpdatedDateInDay: 19,
    description: "Automation tool for repetitive tasks",
  },
  {
    id: "20",
    name: "e-learning-platform",
    isPublic: true,
    language: "PHP",
    size: 10400,
    lastUpdatedDateInDay: 25,
    description: "Online learning management system",
  },
];
